name: Slow CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run a multi-line script
      run: |
        echo Start, sleeping for two minutes.
        python3 -c "from time import sleep; sleep(120)"
        echo Slept for two minutes.
        python3 -c "from time import sleep; sleep(120)"
        echo Slept for two minutes.
        python3 -c "from time import sleep; sleep(120)"
        echo Slept for two minutes.
        python3 -c "from time import sleep; sleep(120)"
        echo Slept for two minutes. One more.
        python3 -c "from time import sleep; sleep(120)"
        echo Done.
